name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  otp_text_field: any
  flutter_carousel_slider: any
  intl_phone_number_input: any
  cached_network_image: any
  shimmer: any
  flutter_screenutil: any
  get: any
  flutter_svg: any
  http: any
  image_picker: any
  intl: any
  provider: any
  shared_preferences: any
  path_provider: any
  idb_sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/catalogue/
    - assets/featured/
    - assets/bottomBarIcons/
    - assets/product/
    - assets/checkOut/
    - assets/onBoarding/

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-ExtraBold.ttf
        weight: 800



